name: potnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - cudatoolkit=11.6.0
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pip:
    - dgl==1.1.1
    - pydantic==1.10.2
    - cython==3.0.0
    - ase==3.22.1
    - jarvis-tools==2022.9.16
    - numpy==1.21.6
    - pandarallel==1.6.3
    - pandas==1.3.5
    - periodictable==1.6.1
    - pymatgen==2021.3.3
    - pytorch-ignite==0.4.10
    - pyyaml==6.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - tqdm==4.64.1
