process_dir: processed  # directory for torch geometric processed dataset
cache_dir: cache  # directory for infinite summation processed files
checkpoint_dir: checkpoint  # directory for checkpoints

dataset: megnet
# JARVIS dataset: dft_3d
# MP dataset: megnet
target: gap pbe
# JARVIS dataset entries: formation_energy_peratom, mbj_bandgap, optb88vdw_bandgap, optb88vdw_total_energy, ehull
# MP dataset entries: e_form, gap pbe
# If using custom dataset, please set this to the corresponding entry name, e.g., target

atom_features: cgcnn

epochs: 500
batch_size: 64
num_workers: 8
weight_decay: 0.0
learning_rate: 1e-3

criterion: mse
optimizer: adamw
scheduler: onecycle

pin_memory: False
write_checkpoint: True
write_predictions: True
store_outputs: True
progress: True
log_tensorboard: False

normalize: False  # scaling the targets by their mean and std
euclidean: False  # disable infinite summation or not
cutoff: 4.0  # local graph cutoff
max_neighbors: 16
infinite_funcs: ["zeta", "zeta", "exp"]
infinite_params: [0.5, 3.0, 3.0]  # Coulomb, London dispersion, Pauli
R: 3  # half of the grid length

model:
  name: potnet
  conv_layers: 3
  rbf_min: -4.0
  rbf_max: 4.0
  potentials: [-0.801, -0.074, 0.145]  # coefficients for infinite summations; should be negative, negative, positive w.r.t. their mathematical form
#  potentials: [ -0.703, -0.0617, 0.142 ]
#  potentials: [-0.816, -0.052, 0.149]
  charge_map: False  # if including information of periodic table
  transformer: False  # enable transformer structure for infinite potential summation; only works when euclidean is False
